from .import cel
from .import cdr
from .import channel
from .import conf
from .import dialplan
from .import extension
from .import incoming_route
from .import menu
from .import outgoing_route
from .import peer
from .import peer_status
from .import peer_registry
from .import queue
from .import res_users
from .import res_partner
from .import server
from .import settings
from .import timeframe
from .import user
from .import security
