{
    'name': 'Asterisk PBX Management Application',
    'summary': '',
    'description': """Use Odoo to Manage your Asterisk servers.""",
    'version': '1.5',
    'category': 'Phone',
    'author': 'Odooist',
    'license': 'OPL-1',
    'depends': ['web', 'bus', 'board'],
    'external_dependencies': {'python': ['humanize']},
    'installable': True,
    'application': True,
    'auto_install': False,
    'data': [
        'security/common.xml',
        'security/asterisk_agent/security.xml',
        'security/asterisk_agent/ir.model.access.csv',
        'security/asterisk_report/security.xml',
        'security/asterisk_report/ir.model.access.csv',
        'security/asterisk_user/security.xml',
        'security/asterisk_user/ir.model.access.csv',
        'security/asterisk_admin/security.xml',
        'security/asterisk_admin/ir.model.access.csv',
        # Views
        'views/views.xml',
        'views/channel.xml',
        'views/cel.xml',
        'views/cdr.xml',
        'views/conf.xml',
        'views/conf_templates.xml',
        'views/extension.xml',
        'views/dialplan.xml',
        'views/incoming_route.xml',
        #'views/ir_cron.xml',
        'views/menu.xml',
        'views/outgoing_route.xml',
        'views/outgoing_route_group.xml',
        'views/peer_status.xml',
        'views/peer_registry.xml',
        'views/peer_views.xml',
        'views/peer_user.xml',
        'views/peer_trunk.xml',
        'views/queue.xml',
        'views/res_partner.xml',
        'views/server.xml',
        'views/settings.xml',
        'views/security.xml',
        'views/templates.xml',
        'views/timeframe.xml',
        'views/user.xml',
        # Data
        'data/timeframe.xml',
    ],
    'demo': [
    ],
    'qweb': [
        'static/src/xml/*.xml',
    ],
    'images': ['static/description/odoo_asterisk.png'],
}
